spring:
  jersey:
    type: filter
    application-path: /api
#  jackson:
#      date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
#      default-property-inclusion: NON_ABSENT
#      serialization:
#        WRITE_DATES_AS_TIMESTAMPS: false
#        INDENT_OUTPUT: true

server:
  port: 9999
  servlet-path: /